### ISSUE TITLE
Migration tracking

### ISSUE THREAD

**Issue by CaptainSpof** [CaptainSpof/dafos#3]
This repository is my attempt to migrate my personal dotfiles/hosts configurations from a `digga` based solution (which is now deprecated) to a solution based on snowfall.

**Systems/hosts:**
- [x] dafoltop · my old laptop which was collecting dust, now promoted to guinea pig
- [x] daftop · my main laptop
- [x] dafbox · my desktop / media server
- [ ] dafpi · a Raspberry Pi 4 board, currently running home assistant
- [ ] dafcointreau · an Orange Pi 5 board, home assistant should be migrated here

**Related Issues & PR:**
- #1 
- #2 
- #4 
- #5 
- #6 
- #8 
- #14 
- #27
- #28 
- #30 
- #40
